version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real-estate-frontend-prod
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DOMAIN=${DOMAIN:-localhost}
      - NGINX_RELOAD_INTERVAL=${NGINX_RELOAD_INTERVAL:-6h}    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      -  /etc/letsencrypt/live/yourdomain.com:/etc/letsencrypt/live/yourdomain.com:ro
      -  /etc/letsencrypt/archive/yourdomain.com:/etc/letsencrypt/archive/yourdomain.com:ro
      - ./dist:/usr/share/nginx/html:ro
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - real-estate-network

networks:
  real-estate-network:
    external: true